<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sell_Dialog</name>
   <tag></tag>
   <elementGuidId>cba81e36-e263-4e0a-a8b2-57e00abb9124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BuySellMainDiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup_theme08_tradecontentRed</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BuySellMainDiv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELLBUYSELLNSENSENSE DerivativesBSEMCX FuturesNCDEX FuturesNSECDS FuturesOFSNormalNormalStoplossSwitch To ROBO Order               Order By Quantity                                     Order By ValueInstrumentInstrumentSymbolSymbolSymbolExpiry DateExpiry DateOption TypeOption TypeStrike PriceStrike PriceProduct TypeAMO DELIVERYAMO DELIVERYAMO INTRADAYAMO MARGINValidityDAYDAYIOCPrice TypeLIMITLIMITMARKETAmountQuantityPriceDisc QtyTrigger PricePlease select scrip.SubmitCancel MoreCloseLTP: LIMIT: 10,196.00ANGEL DP HOLDINGS: 0Block FundBest 5(Combined view)OHLCLimits/MarginNSEBID COUNTBID QTYBID PRICEASK PRICEASK QTYASK COUNTBSEBID COUNTBID QTYBID PRICEASK PRICEASK QTYASK COUNT	Symbol:-Series:-Open-LTQ-52WH-ATP-Close-LTP-52WL-Net Chng(%)-High-TSQ-No.of Trades-LCL-Low-TBQ-Volume-UCL- Span Margin:-Exposure Margin:0.00Total Margin:-Limit (INR):-Note:  Please note that the Margin required figures reflected above is an indicative value per lot for any new open position.existing positions are not considered</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BuySellMainDiv&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='BuySellMainDiv']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BuySellDiv']/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'BuySellMainDiv', '&quot;', ')')])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
